# Permalinks
permalink:        /:year/:month/:day/:title/
relative_permalinks: true

# Setup
title:            The Game Studio
tagline:          Creators of fine games.
url:              http://thegamestudio.co/
paginate:         5
hostname:         http://thegamestudio.co
baseurl:          /
author:
  name:           Zachary Lewis
  url:            https://twitter.com/zachwlewis
  email:          zachwlewis@gmail.com
  
# Conversion
excerpt_separator: "<!--more-->"

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thegamestudio/thegamestudio.github.io
