# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://thegamestudio.co
paginate:         5
baseurl:          /
author:
  name:           Zachary Lewis
  url:            https://twitter.com/zachwlewis
  email:          zachwlewis@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thegamestudio/thegamestudio.github.io
